# Generated by Django 5.2.6 on 2025-09-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitness_goals',
            field=models.TextField(blank=True),
        ),
    ]
