# Generated by Django 5.2.6 on 2025-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_profile_fitness_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
