# Generated by Django 5.2.6 on 2025-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_badge_profile_points_streak_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
